# Replace with your application's base package name
spring:
  application:
    name: book-exchange-platform
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/soutrikroy
    username: soutrikroy
    password: Sharanya@24

server:
  port: 8090

logging:
  level:
    org:
      springframework: INFO
    com:
      example: DEBUG
